### ISSUE TITLE
Support link?

### ISSUE THREAD

**Issue by digitallyelite** [SofianeHamlaoui/Go-undercover#1]
While I think it's awesome that you've pulled the kali-undercover mode out of kali... what exactly is the support me link for?  a sed of kali->go ?  They've done all the work, so it seems a bit odd that you're asking for support.

**Comment by SofianeHamlaoui** [comment]
I just add it to all my repos, it's not at all for the go-undercover :)

**Comment by SofianeHamlaoui** [comment]
and here you go :D I just removed the support link ^^
