### ISSUE TITLE
please support termux

### ISSUE THREAD

**Issue by nimade2333** [SofianeHamlaoui/Go-undercover#6]

**Comment by MeBadDev** [comment]
that wont make sense. Termux is an Android terminal emulator, while Go-undercover is basically just a theme.

**Comment by SofianeHamlaoui** [comment]
> that wont make sense. Termux is an Android terminal emulator, while Go-undercover is basically just a theme.

thank you for your answer, well yeah there is no purpose of doing it if you have no GUI.
