### ISSUE TITLE
how to undo?

### ISSUE THREAD

**Issue by hth2** [SofianeHamlaoui/Go-undercover#8]
I tried the script and find it very useful, thanks for providing it. However sometime I need to go back to the default theme before running the install.sh script. Is it possible?

**Comment by SofianeHamlaoui** [comment]
Hello @hth2,

As shown on the preview GIFS, it's made for a toggle button purpose, in other words you execute the script to unable it and execute it again to undo and go back to the original theme/mode. 

This script was made 5 years ago, so if you think something is in need to change don't hesitate to report it.


Thank you.
